devices:
  - id: eol-1              # unique ID for this device used in WS and MQTT topics
    name: "OWON OEL"       # friendly name for UI more details about device will come from SCPI query if available
    driver: owon_oel       # driver name from drivers/ folder
    port: /dev/ttyOEL1515  # adjust to your /dev/ path
    baud: 115200           # many OWON units use 115200 baud
    serial: 8N1            # optional, defaults to 8N1 if not specified
    seol: "\n"             # send end of line if queries time out, try "\r\n"
    reol: "\n"             # receive end of line if queries time out, try "\r\n"
    model: OEL1515         # optional model override if auto-detect fails
  - id: psu-1
    name: "OWON SPM"
    driver: owon_spm
    port: /dev/ttySPM3103
    baud: 115200
    serial: 8N1
    seol: "\n"
    reol: "\n"
    model: SPM3103
  - id: tenmapsu-1
    name: "TENMA PSU"
    driver: tenma_psu
    port: /dev/tty722540
    baud: 115200
    serial: 8N1
    seol: "\r\n"
    reol: "\n"
    model: 72-2540
  - id: dmm-1
    name: "OWON XDM"
    driver: owon_xdm
    port: /dev/ttyXDM1241
    baud: 115200
    serial: 8N1
    seol: "\r\n"
    reol: "\n"
    model: XDM1241