version: 1
devices:
  - id: eol-1                                # unique ID for this device used in WS and MQTT topics
    name: "OWON OEL"                         # friendly name for UI more details about device will come from SCPI query if available
    driver: owon_oel                         # driver name from drivers/ folder
    port: /dev/ttyOEL1515                    # adjust to your /dev/ path
    baud: 115200                             # many OWON units use 115200 baud
    serial: 8N1                              # optional, defaults to 8N1 if not specified
    model: OEL1515                           # optional model override if auto-detect fails
  - id: psu-1
    name: "OWON SPM"
    driver: owon_spm
    port: /dev/ttySPM3103
    baud: 115200
    serial: 8N1
    model: SPM3103
  - id: tenmapsu-1
    name: "TENMA PSU"
    driver: tenma_72
    port: /dev/tty722540
    baud: 9600
    serial: 8N1
    model: 72-2540
  - id: dmm-1
    name: "OWON XDM"
    driver: owon_xdm
    port: /dev/ttyXDM1241
    baud: 115200
    serial: 8N1
    model: XDM1241